name: Android

jobs:
  build-android:
    name: Android
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - run: npm ci

      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'

      - uses: gradle/gradle-build-action@v3

      - working-directory: android
        run: ./gradlew :app:assembleRelease

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: empower-plant-react-native-android
          path: android/app/build/outputs/apk/release/app-release.apk
          retention-days: 60
