name: Release
on:
  pull_request:
  workflow_dispatch:
    inputs:
      version:
        description: 'The version name to release. E.g. 4.0.2'
        required: true

jobs:
  bump-version:
    runs-on: macos-latest
    name: 'Release a new React Native Empower Plant version'
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - run: npm ci

      - name: Bump Version
        run: |
          git checkout -b release/3.2.0
          npm version 3.2.0
          # # TODO: This should happen after the GH Release is created
          # git checkout main
          # git merge release/3.2.0

  build-android:
    needs: [bump-version]
    uses: ./.github/workflows/build-android.yml
    with:
      ref: release/3.2.0

  # build-ios:
  #   needs: [release]
  #   uses: ./.github/workflows/build-ios.yml

  # publish-release:
  #   needs: [bump-version, build-android, build-ios]
  #   runs-on: macos-latest
  #   steps:
  #     - name: Download iOS App
  #       uses: actions/download-artifact@v4
  #       with:
  #         name: empower-plant-react-native-ios
  #         path: ios/DerivedData/Build/Products/Release-iphonesimulator/sentry_react_native.app

  #     - name: Download Android APK
  #       uses: actions/download-artifact@v4
  #       with:
  #         name: empower-plant-react-native-android
  #         path: android/app/build/outputs/apk/release/app-release.apk

  #     - name: Create Release
  #       run: |
  #         gh release create $PACKAGE_VERSION app/build/outputs/apk/debug/app-debug.apk app/build/outputs/apk/release/app-release.apk -t "$PACKAGE_VERSION" --generate-notes || error_exit "Failed to create GitHub release."
