name: UI Test Android

env:
  MAESTRO_VERSION: 1.39.0

jobs:
  run-ui-test-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup KVM
        shell: bash
        run: |
          # check if virtualization is supported...
          sudo apt install -y --no-install-recommends cpu-checker coreutils && echo "CPUs=$(nproc --all)" && kvm-ok
          # allow access to KVM to run the emulator
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' \
            | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Download APK artifact
        uses: actions/download-artifact@v4
        with:
          name: empower-plant-react-native-android

      - name: Install Maestro
        uses: dniHze/maestro-test-action@bda8a93211c86d0a05b7a4597c5ad134566fbde4 # pin@v1.0.0
        with:
          maestro-version: ${{env.MAESTRO_VERSION}}

      - name: Run tests
        uses: reactivecircus/android-emulator-runner@62dbb605bba737720e10b196cb4220d374026a6d # pin@v2.33.0
        with:
          api-level: 30
          force-avd-creation: false
          disable-animations: true
          disable-spellchecker: true
          target: 'aosp_atd'
          channel: canary # Necessary for ATDs
          emulator-options: >
            -no-window
            -no-snapshot-save
            -gpu swiftshader_indirect
            -noaudio
            -no-boot-anim
            -camera-back none
            -camera-front none
            -timezone US/Pacific
          script: |
            adb install -r -d app-release.apk
            maestro test maestro --debug-output maestro-logs --env=APP_ID=com.sentry_react_native